name: shopzada_dwh

x-airflow-common: &airflow-common
  image: shopzada-airflow:latest
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@shopzada-airflow-db:5432/airflow_meta
    AIRFLOW_UID: 50000
    SHOPZADA_DATA_DIR: /opt/airflow/data
    SHOPZADA_REPO_ROOT: /opt/airflow/repo
    DATA_DIR: /opt/airflow/data
    POSTGRES_HOST: shopzada-db
    POSTGRES_DB: shopzada
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_PORT: 5432
  volumes:
    - ../airflow/dags:/opt/airflow/dags
    - ../airflow/logs:/opt/airflow/logs
    - ../airflow/plugins:/opt/airflow/plugins
    - ../data:/opt/airflow/data:ro
    - ..:/opt/airflow/repo:ro

services:
  shopzada-db:
    container_name: shopzada-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopzada
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10

  shopzada-airflow-db:
    container_name: shopzada-airflow-db
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_meta
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow_meta"]
      interval: 5s
      retries: 10

  shopzada-airflow-init:
    <<: *airflow-common
    container_name: shopzada-airflow-init
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: shopzada-airflow
    depends_on:
      shopzada-airflow-db:
        condition: service_healthy
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db upgrade &&
      airflow users create --username admin --password admin --firstname Shop --lastname Zada --role Admin --email admin@shopzada.local || true &&
      python /opt/airflow/repo/scripts/setup_airflow_connection.py || true
      "

  shopzada-airflow-scheduler:
    <<: *airflow-common
    container_name: shopzada-airflow-scheduler
    command: scheduler
    depends_on:
      shopzada-airflow-init:
        condition: service_completed_successfully
      shopzada-db:
        condition: service_healthy

  shopzada-airflow-webserver:
    <<: *airflow-common
    container_name: shopzada-airflow-webserver
    command: webserver
    depends_on:
      shopzada-airflow-init:
        condition: service_completed_successfully
      shopzada-db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  db_data:
  airflow_db_data:
